import React, { useState } from "react";
import { FormField, Loader } from "../components";
import { useNavigate } from "react-router-dom";
import { preview } from "../assets";
import { BASE_URL, getRandomPrompt } from "../utils";

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: "",
    photo: "",
    prompt: "",
  });

  const [generatingImageFlag, setGeneratingImageFlag] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = () => {};

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt();
    setForm({ ...form, prompt: randomPrompt });
  };

  const generateImage = async () => {
    if (form.prompt) {
      try {
        setGeneratingImageFlag(true);
        const response = await fetch(`${BASE_URL}/api/v1/dalle`, {
          method: "POST",
          headers: {
            "Content-type": "application/json",
          },
          body: JSON.stringify({ prompt: form.prompt }),
        });
        const jsonRes = await response.json();
        console.log({ jsonRes });
        // setForm((prev) => ({...prev, photo: response.json()}))
      } catch (error) {}
    }
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div className="mb-4">
        <h1 className="font-extrabold text-dark-grey text-[32px]">Create</h1>
        <p className="mt-2 text-greyish text-[14px] max-w-[500px]">
          Create imaginative and visually stunning images generated by DALL-E AI
          and share it to the community
        </p>
      </div>
      <form onSubmit={handleSubmit}>
        <FormField
          name="name"
          type="text"
          label="Your Name"
          value={form.name}
          placeholder="John Doe"
          handleChange={handleChange}
        />
        <FormField
          name="prompt"
          type="text"
          label="Prompt"
          value={form.prompt}
          placeholder="A comic book cover of a superhero wearing headphones"
          handleChange={handleChange}
          isSurpriseMe
          handleSurpriseMe={handleSurpriseMe}
        />

        <div
          className="w-64 h-64 border border-gray-300
      rounded relative text-gray-300 
      focus:ring-purple focus:border-purple p-3 flex justify-center items-center"
        >
          {form.photo ? (
            <img src={form.photo} alt={form.photo} />
          ) : (
            <img
              className="w-9/12 h-9/12 object-fill"
              src={preview}
              alt="preview image"
            />
          )}
          {generatingImageFlag && (
            <div className="bg-gray-800 inset-0 absolute opacity-40 flex justify-center items-center">
              <Loader />
            </div>
          )}
        </div>
        <div className="">
          <button
            type="button"
            className="bg-green-700 w-full rounded px-4 py-2 text-white my-3 text-sm"
            onClick={generateImage}
          >
            {generatingImageFlag ? "Generating Image..." : "Generate"}
          </button>
        </div>
        <div className="mt-10">
          <p className="text-sm text-greyish mb-3">
            Once you've generated the image, you can share it with community...
          </p>
          <button
            type="button"
            className="w-full py-2 text-white bg-purple text-sm rounded"
          >
            {loading ? "Sharing" : "Share"}
          </button>
        </div>
      </form>
    </section>
  );
};

export default CreatePost;
