import React, { useState, useEffect } from "react";
import { FormField, Loader } from "../components";

function RenderCards({ data, title }) {
  if (data?.length > 0) {
    return data.posts.map((post) => <Card key={post._id} {...posts} />);
  } else {
    return <h2 className="font-bold text-purple mt-5 text-xl uppercase">{title}</h2>;
  }
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-dark-grey text-[32px]">
          The community showcase
        </h1>
        <p className="mt-2 text-greyish text-[14px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            <h2 className="font-medium text-greyish">
              Showing results for{" "}
              <span className="text-dark-grey">{searchText}</span>
            </h2>
          </>
        )}
        <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
          {searchText ? (
            <RenderCards data={[]} title={"No search result found"} />
          ) : (
            <RenderCards data={[]} title={"No posts found"} />
          )}
        </div>
      </div>
    </section>
  );
};

export default Home;
